### ISSUE TITLE
VEX schema/spec version should be a field in the metadata

### ISSUE THREAD

**Issue by lumjjb** [openvex/spec#20]
Currently there is no way to specify the current version of spec/schema used. Given that we most likely will have iterations and newer versions, we should encode it so that tooling can use it in the appropriate way.

This proposal is to add a field in `Statement` and `Document` to encode a VEX spec version.

**Comment by lumjjb** [comment]
@luhring @puerco @rnjudge @wagoodman thoughts?

**Comment by puerco** [comment]
I would not add it at the statement level because I think one document is expected to be all in one version. But moving forward the context uri will be versioned to do exactly that. I'm planning to do a final pass once the VEX Minimum Elements document is officially published and freeze the spec as v1.0.0. 
After that I will update the context URL to start versioning it. WDYT?

**Comment by lumjjb** [comment]
Yea that sounds good, we are exploring some usecases where a full document isn't necessary, but nonetheless we can still encode it as a document... so unless that pattern becomes more prevalent. i think this proposal for context uri is good

**Comment by puerco** [comment]
Since spec v0.2.0 the context in OpenVEX documents is now versioned :tada:
